### ISSUE TITLE
Remove this repository

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/carbon-elements#8]
This repository only have reference to the [PolymerElements/carbon-route](https://github.com/PolymerElements/carbon-route) element. And `carbon-route` element no longer exists. It redirects to the new [PolymerElements/app-route](https://github.com/PolymerElements/app-route).

I think we should remove this repository and redirects to [PolymerElements/app-elements](https://github.com/PolymerElements/app-elements).

/cc @tjsavage

**Comment by tjsavage** [comment]
Yep good point. Removing now.
